### ISSUE TITLE
music problem

### ISSUE THREAD

**Issue by DutchPatrick** [CodeBrauer/gmod-loadingscreen#13]
I added 3x the same music and called it 1.ogg 2.ogg 3.ogg but its not working

**Comment by CodeBrauer** [comment]
@DutchPatrick currently there is only the option to add 1.jpg - 3.jpg.

An update will coming soon to add automatic image loading frome the img folder

**Comment by brooksy0** [comment]
I still cant hear any music. They're all 1.ogg 2.ogg 3.ogg converted with the link on this thread and still no music

**Comment by brooksy0** [comment]
http://brooklynrp.byethost7.com/index.php

**Comment by CodeBrauer** [comment]
@brooksy0 - Check your FTP file permissons.

The file is not accessible with http (403 forbidden) - the easiest way is to give the file `0777` perms.

**Comment by CodeBrauer** [comment]
@brooksy0 - #14
