### ISSUE TITLE
Music issue - not solved in the other thread

### ISSUE THREAD

**Issue by brooksy0** [CodeBrauer/gmod-loadingscreen#14]
No music is playing, all files are OGG format and its completely quiet. also changed volume but made no difference.
http://brooklynrp.byethost7.com/index.php

**Comment by CodeBrauer** [comment]
You should check your server/file permissons.
http://brooklynrp.byethost7.com/music/1.ogg

On browsing this URL I get an slow request & with `wget` I get  **ERROR 403: Forbidden** - the file has to be accessible.

**Comment by SephirothSG** [comment]
And if all else fails `CHMOD -R 777 *`

**Comment by brooksy0** [comment]
don't worry, this wasnt my issue. All the files were permitted it was the actual hosting i used. i switched to 000webhost and it worked fine. I'd suggest anyone not to you Bytehost, they suck dick

**Comment by brooksy0** [comment]
* byethost7

**Comment by brooksy0** [comment]
Here is my fixed  version http://brooklynrp.net78.net/

**Comment by brooksy0** [comment]
also, come check out my server if anyone gets a chance hehe :)
