### ISSUE TITLE
OpenID

### ISSUE THREAD

**Issue by ethikson** [CodeBrauer/gmod-loadingscreen#15]
Does this need openID implemented?

**Comment by CodeBrauer** [comment]
No. The playername and the information are from the steam web API.

**Comment by ethikson** [comment]
I'm just a bit confused sorry, I went and read the steam web api and from what I can se it relies on open ID, when I connect to my gmod server it just has the static text for the player name, do I need something other than php and html running on my server?

**Comment by CodeBrauer** [comment]
The script works this way:
In your gmod server.cfg you will need the set this line 
```
sv_loadingurl "http://example.com/gmod-loadingscreen/?steamid=%s&mapname=%m"`
```

Garrys Mod Server will replace `%s` by the steamID64 - My script looks up the real profile name with the SteamWebAPI.

Basically you really need only php5.3+ and a php.ini that has `allow_fopen_url` to `On/1`

https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

No openID at all.

**Comment by ethikson** [comment]
Thanks man :)
