### ISSUE TITLE
Player name not showing

### ISSUE THREAD

**Issue by dankerpepers** [CodeBrauer/gmod-loadingscreen#18]
Their name is not showing, it is just saying hello player

**Comment by CodeBrauer** [comment]
This can have multiple reasons:

1. Did you set the `sv_loadingurl` correctly? It should contain the param `%s` for the steamid, just like in the readme.
2. Was the Steam WebAPI available at this moment? Check this [here](http://steamstat.us/). It is sometimes down, then the request gets canceled and it falls back to "Hello Player".
3. Your Steam Web API Key isn't set correctly / not valid.

Working example: http://gabrielw.de/gmod/?steamid=76561198051267973&mapname= ttt_rooftops_a2
