### ISSUE TITLE
photo error

### ISSUE THREAD

**Issue by cl20103B11** [CodeBrauer/gmod-loadingscreen#19]
i put the music file into public_html\music and name is 1.ogg, 2.ogg, 3.ogg,but in preview is no sound

**Comment by CodeBrauer** [comment]
Do have a link?

**Comment by cl20103B11** [comment]
i fix the music problem but it have a photo problem 
link:http://gmodserver.comli.com/

**Comment by CodeBrauer** [comment]
How did you fix the problem with the music/what was the error?

To fix the image problem adjust your HTML... You close the `<h1>` tag to late.

**Comment by cl20103B11** [comment]
it is my internet Browser problem(Microsoft Edge and i just use FireFox to fix it) and can i put MP3 or WAV format to play music?

**Comment by CodeBrauer** [comment]
No. Gmod can only play ogg files.
