### ISSUE TITLE
GMod just shows plain text

### ISSUE THREAD

**Issue by matematrix** [CodeBrauer/gmod-loadingscreen#20]
Hello,

I have an issue, where the loading screen itself is working in the browser, but one day it was just showing plain text in GMOD.
I assume that the PHP is working, because the player name and the map are shown, but everything is just in plain text.

**Comment by CodeBrauer** [comment]
Do you have a link?

I can imagine it had some issues loading the css, but on default it should work fine because it also doesn't use CDNs.

**Comment by matematrix** [comment]
Yes, the link is http://alzlper.com/gmodloading/.

**Comment by matematrix** [comment]
Just to add: I looked into the server console and it gave me a bunch of errors like this:
`[HTML] http://alzlper.com/gmodloading/index.php/js/vendor/jquery-1.10.1...:1: Uncaught SyntaxError: Unexpected token <
`
Maybe this is the cause?

**Comment by CodeBrauer** [comment]
Hmm, don't know your server config - maybe try adding the full URL - in every `src` attribute:

So instead
```html
<script src="js/vendor/jquery-1.10.1.min.js"></script>
```

You try:
```html
<script src="//alzlper.com/gmodloading/js/vendor/jquery-1.10.1.min.js"></script>
```

**Comment by matematrix** [comment]
For me it looks like the server just has a problem with some Java.
Tried your solution, didn't work sadly.
What details of the server config do you need, I can provide them!

**Comment by CodeBrauer** [comment]
Hmm. One more question! Are you sure there is no leading slash on your gmod config?

When I call http://alzlper.com/gmodloading/index.php/ it looks broken like you described in first place

**Comment by matematrix** [comment]
Yeah, I played around a little bit with and experienced that, too. But I already changed that in the server cfg. But I am gonna try it again, thanks for you help until now :)

**Comment by matematrix** [comment]
Sorry, it was my own mistake, I had two server configs, and just edited in one.
Sorry, but thanks for your help! 👍

**Comment by Ghostly082** [comment]
What do you mean "two server configs" I am having the same issue

**Comment by CodeBrauer** [comment]
@Ghostly082 - If you have 2 gmod-servers with 2 different loading screens you need to create two directories with separate loadingscreen URLs.

In this case I assume @matematrix just edited the wrong server.cfg on his server
