### ISSUE TITLE
Just shows HTML Text, no images, no backround or anything, just plain text.

### ISSUE THREAD

**Issue by Ghostly082** [CodeBrauer/gmod-loadingscreen#21]
I have been spending hours and hours trying to figure out this problem. But I have everything coded correctly, I have a domain name. I have a url. And whenever I join my server and see the loading screen. I see something like this.
![problem](https://user-images.githubusercontent.com/30761068/28999541-cd6c8dae-79fe-11e7-89d3-ababa81922d9.PNG)

**Comment by SephirothSG** [comment]
Hey there,

Does the loading screen work as expected in your web browser?

**Comment by Ghostly082** [comment]
No, same issue

**Comment by SephirothSG** [comment]
Would you be able to provide the URL to the page please.

**Comment by Ghostly082** [comment]
Sure! Here

http://darkrploadings.ga/gmod-loadingscreen/?steamid=%s&mapname=%m

**Comment by Ghostly082** [comment]
As you can see, still working on it a little bit

**Comment by SephirothSG** [comment]
It appears that your host (000webhost) is doing something wonky, I would suggest you host your site somewhere else. Preferably _not_ using a free webhosting service.

**Comment by Ghostly082** [comment]
Have any suggestions?

**Comment by SephirothSG** [comment]
I cannot recommend you any specific host without first knowing your needs, nor is this the place to do so.

Do some googling, find a host that provides what you need at a reasonable price, problem solved.

**Comment by SephirothSG** [comment]
@CodeBrauer This can be closed.

**Comment by Ghostly082** [comment]
Thanks for your help guys! :)

**Comment by CodeBrauer** [comment]
Thanks to @SephirothSG for the support 😉
