### ISSUE TITLE
loading bar jam

### ISSUE THREAD

**Issue by cl20103B11** [CodeBrauer/gmod-loadingscreen#23]
I don't know why, but I see my loading bar is jam in 3%.
link:https://loadingscren.000webhostapp.com

**Comment by CodeBrauer** [comment]
I haven't tested the loadingscreen yet, because I have no server. Could you provide a server ip or address to join / to see the error?

**Comment by cl20103B11** [comment]
server ip: 124.244.167.12(i open server only when i have time to play)
